import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import AppProvider from "../components/appProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
            <AppProvider>
      <html lang="en" className="scroll-smooth">
        <body className={roboto.className}>
          <main className="max-w-4xl mx-auto p-4">
            <Toaster position="top-center" toastOptions={{ duration: 3000 }} />
            <Header />
              {children}
            <Footer />
          </main>
        </body>
      </html>
            </AppProvider>
    </ClerkProvider>
  );
}
